config/routes.rb
require 'sidekiq/web'

class SubdomainPresent
	def self.matches?(request)

		request.subdomain.present?

	end
end

class SubdomainBlank
	def self.matches?(request)

		request.subdomain.blank?

	end
end

Rails.application.routes.draw do
	mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq' if Rails.env.development?
	
	constraints(SubdomainPresent) do

		root 'queries#index', as: :subdomain_root
		devise_for :users
		resources :users, only: :index
		resources :queries, except: [:show, :destroy] do
			resources :leads, only: [:index, :show]
		end

	end

	constraints(SubdomainBlank) do

		root 'home#index'
		resources :accounts, only: [:new, :create]

	end

end

app/models/lead.rb
class Lead < ActiveRecord::Base

	before_validation :set_photo
	
	belongs_to :query
	has_many :lead_certifications, dependent: :destroy
	has_many :lead_companies, dependent: :destroy
	has_many :lead_educations, dependent: :destroy
	has_many :lead_groups, dependent: :destroy
	has_many :lead_languages, dependent: :destroy
	has_many :lead_organisations, dependent: :destroy
	has_many :lead_skills, dependent: :destroy
	has_many :lead_websites, dependent: :destroy

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :linkedin_url, presence: true

	def name

		"#{first_name} #{last_name}"
		
	end

=begin
	# replaced w/ scopes in lead_company
	def current_positions
		
		positions = []
		self.lead_companies.each do |position|
			unless position.end_date < Date.today
				positions << position
			end
		end

		positions
	end

	def past_positions

		positions = []
		self.lead_companies.each do |position|
			unless position.end_date.nil?
				positions << position
			end
		end

		positions
		
	end
=end

	private

	def set_photo

		if self.photo_url =~ /(ghost_person)/i
			self.photo_url = ""
		end

	end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

	def index

		@query = Query.find(params[:query_id])
		@leads = @query.leads
		
	end

	def show

		@lead = Lead.find(params[:id])
		
	end
end

app/helpers/lead_helper.rb
module LeadHelper

	def lead_photo(lead)

		lead.photo_url.empty? ? "https://static.licdn.com/scds/common/u/images/themes/katy/ghosts/person/ghost_person_200x200_v1.png" : "#{lead.photo_url}"
		
	end
end

app/views/leads/index.html.erb
<div class="col-md-12 leads">

	<h1 class="text-xlarge">
		<%= @query.name %>: Leads
		<span class="text-xxlarge"><%= @leads.count %></span>
	</h1><!-- ./h1 -->

	<% if @leads.empty? %>
		<ul class="list-group">
			<li class="list-group-item">No leads for this query!</li>
		</ul>
	<% else %>
		<% @leads.each do |lead| %>
			<div class="col-md-4 lead">
				<div class="lead-container">
					<%= image_tag lead_photo(lead), alt: "#{lead.name}" %>
					<div class="mask mask-1"></div>
					<div class="mask mask-2"></div>
					<div class="content">
						<h3><%= lead.name %></h3>
						<p><%= lead.headline %><br/><%= lead.location %>, <%= lead.country %></p>
						<%= link_to "View", query_lead_path(lead.query, lead), class: "info" %>
					</div><!-- ./content -->
				</div><!-- ./lead-container -->
			</div><!-- ./lead -->
		<% end %>
	<% end %>
</div><!-- ./col-md-12 -->

app/views/leads/show.html.erb
<div class="col-md-12 lead">

	<h1 class="text-xlarge">
		<%= @lead.name %>
		<span class="text-medium"><%= @lead.location %> <%= ", #{@lead.country}" unless @lead.country.empty? %></span>
	</h1><!-- ./h1 -->

	<div class="lead-info">

		<div class="lead-photo">
			<%= image_tag lead_photo(@lead), alt: "#{@lead.name}" %>
			<%= link_to @lead.linkedin_url, class: "btn btn-social-icon btn-linkedin" do %>
				<i class="fa fa-linkedin"></i>
			<% end %>
		</div><!-- ./lead-photo -->

		<h2 class="text-medium center"><%= @lead.headline %></h2>

		<div class="col-md-8 col-md-offset-2 panel panel-default">
			<div class="panel-body">

				<!-- Summary -->
				<% unless @lead.summary.nil? %>
					<h3>Summary</h3>
					<p><%= @lead.summary %></p>
				<% end %>
				
				<!-- Current Positions -->
				<% unless @lead.lead_companies.is_current.empty? %>
					<h3>Current Positions</h3>
					<ul>
						<% @lead.lead_companies.is_current.each do |position| %>
							<li><%= position.title %> at <%= position.company %></li>
						<% end %>
					</ul>
				<% end %>
				
				<!-- Past Positions -->
				<% unless @lead.lead_companies.is_past.empty? %>
					<h3>Past Positions</h3>
					<ul>
						<% @lead.lead_companies.is_past.each do |position| %>
							<li><%= position.title %> <%= " at #{position.company}" unless position.company.nil? %></li>
						<% end %>
					</ul>
				<% end %>
				
				<!-- Skills -->
				<% unless @lead.lead_skills.empty? %>
					<h3>Skills</h3>
					<ul>
						<% @lead.lead_skills.each do |skill| %>
							<li><%= skill.skill %></li>
						<% end %>
					</ul>
				<% end %>

				<!-- Certifications -->
				<% unless @lead.lead_certifications.empty? %>
					<h3>Certifications</h3>
					<ul>
						<% @lead.lead_certifications.each do |cert| %>
							<li><%= cert.name %></li>
						<% end %>
					</ul>
				<% end %>

				<!-- Education -->
				<% unless @lead.lead_educations.empty? %>
					<h3>Education</h3>
					<ul>
						<% @lead.lead_educations.each do |ed| %>
							<li>
								<%= ed.name %>
								<%= "<br/>#{ed.description}".html_safe unless ed.description.empty? %>
								<%= "<br/>#{ed.period}".html_safe unless ed.period.empty? %>
							</li>
						<% end %>
					</ul>
				<% end %>

				<!-- Languages -->
				<% unless @lead.lead_languages.empty? %>
					<h3>Languages</h3>
					<ul>
						<% @lead.lead_languages.each do |lang| %>
							<li><%= lang.language %> <%= " | #{lang.proficiency}" unless lang.proficiency.empty? %></li>
						<% end %>
					</ul>
				<% end %>

				<!-- Organisations -->
				<% unless @lead.lead_organisations.empty? %>
					<h3>Organisations</h3>
					<ul>
						<% @lead.lead_organisations.each do |org| %>
							<li>
								<%= org.name %> 
								<%= " | #{org.start_date}" unless org.start_date.empty? %> 
								<%= " - #{org.end_date}" unless org.end_date.empty? %>
							</li>
						<% end %>
					</ul>
				<% end %>

				<!-- Websites -->
				<% unless @lead.lead_websites.empty? %>
					<h3>Websites</h3>
					<ul>
						<% @lead.lead_websites.each do |www| %>
							<li><%= link_to www.site, www.site %></li>
						<% end %>
					</ul>
				<% end %>

				<!-- Groups -->
				<% unless @lead.lead_groups.empty? %>
					<h3>Watering Holes</h3>
					<ul>
						<% @lead.lead_groups.each do |grp| %>
							<li><%= link_to grp.name, grp.link %></li>
						<% end %>
					</ul>
				<% end %>


			</div><!-- ./panel-body -->
		</div><!-- ./panel -->

	</div><!-- ./lead-info -->

</div><!-- ./col-md-12 -->