config/routes.rb
require 'sidekiq/web'

class SubdomainPresent
	def self.matches?(request)

		request.subdomain.present?

	end
end

class SubdomainBlank
	def self.matches?(request)

		request.subdomain.blank?

	end
end

Rails.application.routes.draw do
	mount Sidekiq::Web, at: '/sidekiq', as: 'sidekiq' if Rails.env.development?
	
	constraints(SubdomainPresent) do

		root 'queries#index', as: :subdomain_root
		devise_for :users
		resources :users, only: :index
		resources :queries, except: [:show, :destroy] do
			resources :leads, only: [:index, :show]
		end

	end

	constraints(SubdomainBlank) do

		root 'home#index'
		resources :accounts, only: [:new, :create]

	end

end

app/models/account.rb
class Account < ActiveRecord::Base
	before_validation :downcase_subdomain

	RESTRICTED_SUBDOMAINS = %w(www)

	belongs_to :owner, class_name: 'User'
	has_many :temp_leads

	validates :owner, presence: true
	validates :subdomain, presence: true,
						  uniqueness: { case_sensitive: false },
						  format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
						  exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }

    accepts_nested_attributes_for :owner

    private

    def downcase_subdomain

    	self.subdomain = subdomain.try(:downcase)
    	
    end

end

app/models/lead.rb
class Lead < ActiveRecord::Base

	before_validation :set_photo
	
	belongs_to :query
	has_many :lead_certifications, dependent: :destroy
	has_many :lead_companies, dependent: :destroy
	has_many :lead_educations, dependent: :destroy
	has_many :lead_groups, dependent: :destroy
	has_many :lead_languages, dependent: :destroy
	has_many :lead_organisations, dependent: :destroy
	has_many :lead_skills, dependent: :destroy
	has_many :lead_websites, dependent: :destroy

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :linkedin_url, presence: true

	def name

		"#{first_name} #{last_name}"
		
	end

=begin
	# replaced w/ scopes in lead_company
	def current_positions
		
		positions = []
		self.lead_companies.each do |position|
			unless position.end_date < Date.today
				positions << position
			end
		end

		positions
	end

	def past_positions

		positions = []
		self.lead_companies.each do |position|
			unless position.end_date.nil?
				positions << position
			end
		end

		positions
		
	end
=end

	private

	def set_photo

		if self.photo_url =~ /(ghost_person)/i
			self.photo_url = ""
		end

	end

end

app/models/lead_certification.rb
class LeadCertification < ActiveRecord::Base

  belongs_to :lead

  validates :name, presence: true
  
end

app/models/lead_company.rb
class LeadCompany < ActiveRecord::Base

  belongs_to :lead

  validates :title, presence: true

  scope :is_past, lambda { where("end_date <= ?", Date.today) }
  scope :is_current, lambda { where("end_date > created_on") }

end

app/models/lead_education.rb
class LeadEducation < ActiveRecord::Base

  belongs_to :lead

end

app/models/lead_group.rb
class LeadGroup < ActiveRecord::Base

  belongs_to :lead

  validates :name, presence: true
  validates :link, presence: true

end

app/models/lead_language.rb
class LeadLanguage < ActiveRecord::Base

  belongs_to :lead

  validates :language, presence: true

end

app/models/lead_organisation.rb
class LeadOrganisation < ActiveRecord::Base

  belongs_to :lead

  validates :name, presence: true

end

app/models/lead_skill.rb
class LeadSkill < ActiveRecord::Base

  belongs_to :lead

  validates :skill, presence: true

end

app/models/lead_website.rb
class LeadWebsite < ActiveRecord::Base

  belongs_to :lead

  validates :site, presence: true

end

app/models/query.rb
require "scraper/search_scraper"
class Query < ActiveRecord::Base

	after_create(:get_leads)
	has_many :leads

	validates :name, presence: true
	validates :locality, presence: true,
						 format: { with: /\A[a-z\-\,\s]+\Z/i, message: 'contains invalid characters' }
	validates :skill, presence: true,
					  format: { with: /\A[a-z\-\.\s]+\Z/i, message: 'contains invalid characters' }
	validates :account_id, presence: true

	scope :not_archived, lambda { where(:archived => false) }

	scope :total_leads, lambda { Lead.where(:account_id => self.id) }

	def is_processed

		Apartment::Tenant.switch('public')
		no_temp_leads = TempLead.where("query_id = ? AND account_id = ?", 
			self.id, Account.find(self.account_id)).count > 0 ? false : true
		self.processed and no_temp_leads

	end

	private

	def get_leads

		QueryProcess.perform_async('yahoo', self.id)

	end

end

app/models/temp_lead.rb
class TempLead < ActiveRecord::Base
	
	belongs_to :account

	validates_presence_of(:url, :account_id)

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :validatable

  validates :name, presence: true

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!, only: :index
	
	def index	
	end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

	def index

		@query = Query.find(params[:query_id])
		@leads = @query.leads
		
	end

	def show

		@lead = Lead.find(params[:id])
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

		@users = User.all
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, class: "alert alert-dismissable #{bootstrap_class_for(name)}", role: "alert"){
          concat content_tag(:button, type: "button", class: "close", data: {dismiss: "alert"}){
            concat content_tag(:span, "aria-hidden" => "true"){ "&times;".html_safe }
            concat content_tag(:span, "Close", class: "sr-only")
          }
          concat msg
        }
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end

  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-error"
      when "alert"
        "alert-block"
      when "notice"
        "alert-info"
    end
  end
end

app/helpers/lead_helper.rb
module LeadHelper

	def lead_photo(lead)

		lead.photo_url.empty? ? "https://static.licdn.com/scds/common/u/images/themes/katy/ghosts/person/ghost_person_200x200_v1.png" : "#{lead.photo_url}"
		
	end
end

app/helpers/query_helper.rb
module QueryHelper

	def query_process_status(query)

		if query.is_processed
			
			content_tag :i, '', class: "glyphicon glyphicon-ok color-success"
		else
			content_tag :div, class: "progress" do
				content_tag :div, class: "progress-bar progress-bar-striped active", role: "progressbar", style: "width:45%" do
					content_tag :span, class: "sr-only" do
						"45% complete"
					end
				end
			end
		end
	end

	def query_leads(query)

		Apartment::Tenant.switch(request.subdomain)
		total_leads = query.leads.count

		if total_leads > 0
			link_to query_leads_path(query, class: "query-tool") do
				content_tag(:i, '', class: 'glyphicon glyphicon-user')
			end
		end

	end

end

app/helpers/user_helper.rb
module UserHelper

	def user_status(user)
		
		if current_account.owner == user || user.invitation_accepted?
			content_tag(:span, '', class: 'glyphicon glyphicon-ok color-success')
		else
			'Invitation Pending'
		end

	end
end

app/views/home/index.html.erb
<div class="col-md-12">
	<div class="jumbotron extra-margin-top">
    	<h1>LeadLocate</h1>
    	<h2>Discover new leads</h2>
    	<p><%= link_to 'Create Account', new_account_path, class: 'btn btn-primary btn-lg' %></p>
  	</div><!-- ./jumbotron -->
</div><!-- ./col-md-12 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeadLocate</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="container">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'LeadLocate', root_path, class: 'navbar-brand' %>
        
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-custom"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
        </div><!-- ./navbar-header -->
        <div class="collapse navbar-collapse navbar-custom">
          <% if user_signed_in? %>
            <div class="pull-right right-buttons">
              <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn' %>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Queries <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Your Queries', queries_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "New Query", new_query_path %>
                    </li>
                  </ul>
                </li>
                <li><%= link_to 'Users', users_path %></li>
            </ul><!-- ./navbar-right -->
          <% end %>
        </div><!-- ./navbar-collapse -->
      </div><!-- ./container-fluid -->
    </nav><!-- ./navbar -->
  </header><!-- ./container -->

  <div class="main container">
    <%= flash_messages if show_layout_flash? %>

    <div class="row">
      <%= yield %>
    </div><!-- ./row -->
  </div><!-- ./container -->
</body>
</html>